repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.27.0
    hooks:
      - id: gitleaks

#  - repo: https://github.com/kamadorueda/alejandra
#    rev: 3.1.0
#    hooks:
#      - id: alejandra

  - repo: https://github.com/astro/deadnix
    rev: v1.3.0
    hooks:
      - id: deadnix
        stages: [pre-commit]

  - repo: https://github.com/fidgetingbits/pre-commit-statix
    rev: v1.0.0
    hooks:
      - id: statix-check